; PHP custom settings for Laravel

[PHP]
post_max_size = 100M
upload_max_filesize = 100M
max_execution_time = 300
memory_limit = 512M
max_input_vars = 3000

; Timezone
date.timezone = Asia/Jakarta

; OPcache settings (for performance in production)
[opcache]
opcache.enable = 1
opcache.revalidate_freq = 0
opcache.validate_timestamps = 0
opcache.max_accelerated_files = 10000
opcache.memory_consumption = 192
opcache.interned_strings_buffer = 16
opcache.fast_shutdown = 1
